# DO NOT edit this file using any Microsoft Windows editor, different eol characters will break it
# parse wsdl file and generate c++ header file
wsdl2h ./../../lib/wsdl/ws_home_assistant_1.wsdl -n ha -N ha -f -g -o webservice_gsoap.h
# generate c++ source code from the header file
soapcpp2 -j -SL -v -b -x -I/usr/local/share/gsoap/import -d./src webservice_gsoap.h
